### ISSUE TITLE
Update Plan 更新计划 - Week37

### ISSUE THREAD

**Issue by Zeyi-Lin** [Zeyi-Lin/HivisionIDPhotos#78]
> 欢迎大家认领任务与提交PR，共同打造更好的HivisionIDPhotos开源社区生态！
> 2024.9.9~9.15

## Docs
- [x] API文档的日文版
- [x] API文档的韩文版

## 算法
- [x] 加水印
- [x] 简单美颜算法 - 美白
- [x] 更多模型
  - [x] Birefnet
  - [x] Retinaface
- [x] 照片dpi设置

## UI & 交互逻辑
- [x] 高级参数选项 - 可调节人脸与证件照占比、头顶与顶部距离等高级参数
- [x] 支持在Gradio上下载透明图

## API
- [x] set_kb-照片KB设置，输入一张RGB图像，设置它的KB大小
- [x] watermark-加水印
- [x] idphoto接口-高清照可选项

## GPU
- [x] 明确项目未来的GPU推理方案

**Comment by Nexisato** [comment]
- [ ] 支持在Gradio上看到推理性能（如在XXX设备，XX分辨率，共计XX毫秒，默认隐藏）
 - [ ] 照片dpi设置
预计 09.10 前交付

**Comment by Zeyi-Lin** [comment]
有开发者PR了一个水印算法：https://github.com/Zeyi-Lin/HivisionIDPhotos/pull/83

**Comment by dscao** [comment]
照片dpi设置，我理解的应该是6寸排版照中需要有这个，方便直接给到冲印部门或门店出片。需要再处理的照片对dpi的设置就没没那么重要，反正后期ps中处理时做印前会设置好dpi及尺寸的。我这边目前常用的是5寸排版照，是否可以同时增加一个5寸排版照的输出。这样2个排版照还可以方便比较来选择最经济的方式。

我利用 Pillow 加了dpi设置：
    image = Image.fromarray(white_background)
    DPI = (dpi, dpi)  
    image.save(f'output_{layout_width}_with_dpi_{dpi}.jpg', 'JPEG', dpi=DPI)
    return f'output_{layout_width}_with_dpi_{dpi}.jpg'
   
但每次会在项目目录中保存一次图片，感觉不清爽，还没找到更好的方法实现dpi。

另外我们这边影楼（发外省厂家的产品也是）目前普遍使用dpi=254像素/英寸（ 好处是像素值与实际尺寸更方便查看，1000px就是10cm），传统的印刷厂用dpi=300像素/英寸，dpi设置建议使用这两个选项，其它更多dpi可以有但好像并无实际意义。 dpi有了之后，照片尺寸就需要从像素改成cm或mm，实际像素需要根据所选的dpi计算。

**Comment by Zeyi-Lin** [comment]
> 照片dpi设置，我理解的应该是6寸排版照中需要有这个，方便直接给到冲印部门或门店出片。需要再处理的照片对dpi的设置就没没那么重要，反正后期ps中处理时做印前会设置好dpi及尺寸的。我这边目前常用的是5寸排版照，是否可以同时增加一个5寸排版照的输出。这样2个排版照还可以方便比较来选择最经济的方式。
> 
> 我利用 Pillow 加了dpi设置： image = Image.fromarray(white_background) DPI = (dpi, dpi) image.save(f'output_{layout_width}_with_dpi_{dpi}.jpg', 'JPEG', dpi=DPI) return f'output_{layout_width}_with_dpi_{dpi}.jpg'
> 
> 但每次会在项目目录中保存一次图片，感觉不清爽，还没找到更好的方法实现dpi。
> 
> 另外我们这边影楼（发外省厂家的产品也是）目前普遍使用dpi=254像素/英寸（ 好处是像素值与实际尺寸更方便查看，1000px就是10cm），传统的印刷厂用dpi=300像素/英寸，dpi设置建议使用这两个选项，其它更多dpi可以有但好像并无实际意义。 dpi有了之后，照片尺寸就需要从像素改成cm或mm，实际像素需要根据所选的dpi计算。

Get！
